// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	FAQ "github.com/daffashafwan/pointcuan/business/FAQ"

	mock "github.com/stretchr/testify/mock"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, domain
func (_m *Usecase) Create(ctx context.Context, domain FAQ.Domain) (FAQ.Domain, error) {
	ret := _m.Called(ctx, domain)

	var r0 FAQ.Domain
	if rf, ok := ret.Get(0).(func(context.Context, FAQ.Domain) FAQ.Domain); ok {
		r0 = rf(ctx, domain)
	} else {
		r0 = ret.Get(0).(FAQ.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, FAQ.Domain) error); ok {
		r1 = rf(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *Usecase) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetActive provides a mock function with given fields: ctx
func (_m *Usecase) GetActive(ctx context.Context) ([]FAQ.Domain, error) {
	ret := _m.Called(ctx)

	var r0 []FAQ.Domain
	if rf, ok := ret.Get(0).(func(context.Context) []FAQ.Domain); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]FAQ.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: ctx
func (_m *Usecase) GetAll(ctx context.Context) ([]FAQ.Domain, error) {
	ret := _m.Called(ctx)

	var r0 []FAQ.Domain
	if rf, ok := ret.Get(0).(func(context.Context) []FAQ.Domain); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]FAQ.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, domain, id
func (_m *Usecase) Update(ctx context.Context, domain FAQ.Domain, id int) (FAQ.Domain, error) {
	ret := _m.Called(ctx, domain, id)

	var r0 FAQ.Domain
	if rf, ok := ret.Get(0).(func(context.Context, FAQ.Domain, int) FAQ.Domain); ok {
		r0 = rf(ctx, domain, id)
	} else {
		r0 = ret.Get(0).(FAQ.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, FAQ.Domain, int) error); ok {
		r1 = rf(ctx, domain, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
